"""QA helpers: parse the audio contract in Docs/ASSETS.md, check outputs, write the manifest."""
import csv
import os
import re

from common import REPO, OUT_ROOT


def required_from_assets_md(path=os.path.join(REPO, "Docs", "ASSETS.md")):
    """Return the set of 'Category/name.ext' files the asset contract requires."""
    text = open(path, encoding="utf-8").read()
    sec = text.split("## Audio", 1)[1]
    sec = re.split(r"\n## ", sec, 1)[0]
    # user supplied files (before the "Generated" paragraph) are copied verbatim -> .mp3
    user_part, gen_part = sec.split("Generated", 1)
    return _parse(user_part, "mp3") | _parse(gen_part, "ogg")


def _parse(sec, ext):
    # join wrapped bullet lines
    bullets, cur = [], ""
    for line in sec.splitlines():
        if line.startswith("* "):
            if cur:
                bullets.append(cur)
            cur = line[2:]
        elif line.startswith("  ") and cur:
            cur += " " + line.strip()
        else:
            if cur:
                bullets.append(cur)
            cur = ""
    if cur:
        bullets.append(cur)
    out = set()
    for b in bullets:
        cat = None
        tokens = re.findall(r"`([^`]+)`(\s*…\s*`([^`]+)`)?", b)
        for tok, rng_part, tok2 in tokens:
            if tok.startswith("Audio/"):
                parts = tok.split("/")
                cat, name = parts[1], parts[2]
            else:
                name = tok
            if cat is None:
                continue
            names = []
            m = re.match(r"(.*)<surface>_<1\.\.(\d)>", name)
            if m:
                surf = re.search(r"\{([^}]*)\}", b).group(1)
                for s in [s.strip() for s in surf.split(",")]:
                    names += [f"{s}_{i}" for i in range(1, int(m.group(2)) + 1)]
            elif re.search(r"_<1\.\.(\d)>", name):
                base, k = re.match(r"(.*)_<1\.\.(\d)>", name).groups()
                names += [f"{base}_{i}" for i in range(1, int(k) + 1)]
            elif tok2:
                m1 = re.match(r"(.*)_(\d+)$", name)
                m2 = re.match(r"(?:(.*)_)?(\d+)$", tok2)
                base = m1.group(1)
                names += [f"{base}_{i}" for i in range(int(m1.group(2)), int(m2.group(2)) + 1)]
            elif re.fullmatch(r"\d+", name):  # bare "3" closing a range already expanded
                continue
            else:
                names.append(name)
            for nm in names:
                out.add(f"{cat}/{nm}.{ext}")
    return out


def existing_files(root=OUT_ROOT):
    found = set()
    for d, _, files in os.walk(root):
        for f in files:
            if f.endswith((".ogg", ".mp3")):
                found.add(os.path.relpath(os.path.join(d, f), root).replace(os.sep, "/"))
    return found


def check(stats_list, root=OUT_ROOT):
    """Return a list of problem strings (empty = all good)."""
    problems = []
    req = required_from_assets_md()
    have = existing_files(root)
    for r in sorted(req - have):
        problems.append(f"MISSING {r}")
    for e in sorted(have - req):
        problems.append(f"EXTRA (not in ASSETS.md) {e}")
    for s in stats_list:
        if s.get("ext") != "ogg":
            continue
        p = s["path"]
        if s["peak_db"] < -20 or s["rms_db"] < -55:
            problems.append(f"TOO QUIET {p} peak={s['peak_db']:.1f} rms={s['rms_db']:.1f}")
        if s["peak_db"] > -0.05 or s["clip_frac"] > 0.0005:
            problems.append(f"CLIPPING {p} peak={s['peak_db']:.2f} clip_frac={s['clip_frac']:.4f}")
        if s["loop"] and s["seam"] is not None and s["seam"] > 3.0:
            problems.append(f"LOOP SEAM {p} seam={s['seam']:.2f}")
        if not s["len_ok"]:
            problems.append(f"LENGTH MISMATCH {p}")
    return problems


def write_manifest(stats_list, problems, md_path, csv_path):
    rows = sorted(stats_list, key=lambda s: s["path"])
    total = sum(s["bytes"] for s in rows)
    gen = sum(s["bytes"] for s in rows if s["ext"] == "ogg")
    cols = ["file", "kind", "duration_s", "channels", "sample_rate", "peak_dBFS", "LUFS", "centroid_Hz", "loop",
            "loop_seam", "size_KB", "description"]
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for s in rows:
            w.writerow(_row(s))
    lines = ["# Audio manifest (generated by build_audio.py — do not edit)", "",
             f"{len(rows)} files, total {total / 1e6:.2f} MB (generated .ogg: {gen / 1e6:.2f} MB).", "",
             "`loop_seam` = |last-first sample| / 90th percentile sample step of the decoded file "
             "(≈1 means the wrap is indistinguishable from any other sample step).", ""]
    if problems:
        lines += ["## QA problems", ""] + [f"* {p}" for p in problems] + [""]
    else:
        lines += ["QA: every file listed in Docs/ASSETS.md exists; no silent, clipped or seamed files.", ""]
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("|" + "---|" * len(cols))
    for s in rows:
        lines.append("| " + " | ".join(str(v) for v in _row(s)) + " |")
    open(md_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def _row(s):
    return [
        f"{s['path']}.{s['ext']}", s.get("kind", "generated"), f"{s['dur']:.2f}", s["ch"], s["sr"],
        f"{s['peak_db']:.1f}", f"{s['lufs']:.1f}", f"{s['centroid']:.0f}", "yes" if s["loop"] else "",
        f"{s['seam']:.2f}" if s.get("seam") is not None else "", f"{s['bytes'] / 1024:.0f}", s.get("desc", ""),
    ]
