using UnityEngine;

namespace PrisonersOfOmar.Characters
{
    /// <summary>Pixel rectangle in a character atlas (origin = TOP-LEFT of the PNG, like an image editor).</summary>
    public struct AtlasRect
    {
        public int X, Y, W, H;
        public AtlasRect(int x, int y, int w, int h) { X = x; Y = y; W = w; H = h; }

        /// <summary>
        /// Atlas UV of a point given in region-local coordinates (u to the right, v up, both 0..1).
        /// Inset by half a texel so point sampling never bleeds into the neighbouring region.
        /// </summary>
        public Vector2 UV(float u, float v)
        {
            float px = X + 0.5f + Mathf.Clamp01(u) * (W - 1);
            float py = Y + 0.5f + (1f - Mathf.Clamp01(v)) * (H - 1);
            return new Vector2(px / CharacterAtlas.Size, 1f - py / CharacterAtlas.Size);
        }
    }

    /// <summary>
    /// Layout of the 256x256 character atlases in Resources/Textures/Characters (generated by
    /// Tools/AssetPipeline/characters/build_characters.py). MUST stay in sync with Tools/AssetPipeline/characters/atlas.py.
    /// Cylindrical strips: u = 0/1 at the back seam, 0.5 at the front, the character's right side (+X) at u &lt; 0.5;
    /// v from the bottom ring (0) to the top ring (1).
    /// </summary>
    public static class CharacterAtlas
    {
        public const int Size = 256;

        public static readonly AtlasRect Head = new AtlasRect(0, 0, 128, 96);
        public static readonly AtlasRect Torso = new AtlasRect(128, 0, 128, 112);
        public static readonly AtlasRect Leg = new AtlasRect(0, 96, 64, 128);
        public static readonly AtlasRect Arm = new AtlasRect(64, 96, 48, 112);
        public static readonly AtlasRect Rope = new AtlasRect(112, 96, 16, 112);
        public static readonly AtlasRect Hand = new AtlasRect(64, 208, 32, 32);
        public static readonly AtlasRect Swatch = new AtlasRect(96, 208, 32, 48);
        public static readonly AtlasRect Foot = new AtlasRect(0, 224, 64, 32);
        /// <summary>Cutout: hair strands (root at v = 1, ragged tips at the bottom).</summary>
        public static readonly AtlasRect Hair = new AtlasRect(128, 112, 64, 64);
        /// <summary>Cutout: long hair panel (prisoners 2 / 3), Omar's apron, corpse rags.</summary>
        public static readonly AtlasRect Extra = new AtlasRect(192, 112, 64, 144);
        /// <summary>Cutout: glasses front (top 64x24).</summary>
        public static readonly AtlasRect Glasses = new AtlasRect(128, 176, 64, 24);
        /// <summary>Cutout: Omar's gathered sack skirt / bangs / hair tufts (64x56).</summary>
        public static readonly AtlasRect Skirt = new AtlasRect(128, 200, 64, 56);

        public static readonly AtlasRect FootSide = new AtlasRect(0, 224, 32, 32);
        public static readonly AtlasRect FootTop = new AtlasRect(32, 224, 32, 32);

        // 16x16 flat colour cells inside Swatch
        public static readonly AtlasRect SwatchDark = new AtlasRect(96, 208, 16, 16);
        public static readonly AtlasRect SwatchWhite = new AtlasRect(112, 208, 16, 16);
        public static readonly AtlasRect SwatchMetal = new AtlasRect(96, 224, 16, 16);
        public static readonly AtlasRect SwatchBlood = new AtlasRect(112, 224, 16, 16);
        public static readonly AtlasRect SwatchSkin = new AtlasRect(96, 240, 16, 16);
        public static readonly AtlasRect SwatchHair = new AtlasRect(112, 240, 16, 16);

        // ---- tube tables (see atlas.py) ----
        public const int HeadSides = 12;
        /// <summary>u of head ring vertex i (angle 180 - 30 i degrees). Front-weighted: the face gets most texels.</summary>
        public static readonly float[] HeadU = { 0f, 0.045f, 0.09f, 0.16f, 0.27f, 0.385f, 0.5f, 0.615f, 0.73f, 0.84f, 0.91f, 0.955f, 1f };
        /// <summary>Head rings: height in head units (chin 0, crown 1, neck negative) ...</summary>
        public static readonly float[] HeadRingY = { -0.50f, -0.22f, 0f, 0.17f, 0.31f, 0.45f, 0.58f, 0.74f, 0.88f, 1f };
        /// <summary>... and their v in the Head strip.</summary>
        public static readonly float[] HeadRingV = { 0f, 0.06f, 0.12f, 0.27f, 0.393f, 0.516f, 0.63f, 0.77f, 0.894f, 1f };

        public const int TorsoSides = 12;
        /// <summary>Torso rings: fraction crotch (0) .. neck base (1); also their v.</summary>
        public static readonly float[] TorsoT = { 0f, 0.12f, 0.26f, 0.40f, 0.55f, 0.68f, 0.80f, 0.93f, 1f };
        public const int LegSides = 8;
        /// <summary>Leg rings: ankle (0) .. hip (1), knee at 0.5.</summary>
        public static readonly float[] LegT = { 0f, 0.12f, 0.30f, 0.42f, 0.50f, 0.58f, 0.75f, 0.90f, 1f };
        public const int ArmSides = 8;
        /// <summary>Arm rings: wrist (0) .. shoulder (1), elbow at 0.5.</summary>
        public static readonly float[] ArmT = { 0f, 0.20f, 0.35f, 0.50f, 0.65f, 0.82f, 1f };

        /// <summary>Face landmarks used for the glasses / sack eye holes (head space: degrees, head units).</summary>
        public const float EyeTheta = 21f;
        public const float EyeY = 0.45f;

        public static string TexturePath(CharacterSkin skin)
        {
            switch (skin)
            {
                case CharacterSkin.Prisoner1: return "Textures/Characters/prisoner1";
                case CharacterSkin.Prisoner2: return "Textures/Characters/prisoner2";
                case CharacterSkin.Prisoner3: return "Textures/Characters/prisoner3";
                case CharacterSkin.Prisoner4: return "Textures/Characters/prisoner4";
                default: return "Textures/Characters/omar";
            }
        }

        public static string TexturePath(FigureKind kind)
        {
            switch (kind)
            {
                case FigureKind.BurntMannequin: return "Textures/Characters/mannequin_burnt";
                case FigureKind.Mannequin: return "Textures/Characters/mannequin";
                default: return "Textures/Characters/corpse";
            }
        }
    }
}
